### PR TITLE
Fix table caption font and add a example for table.

### PR DESCRIPTION
**Pull request by summershrimp**
修复了表格标题的字号，应为五号黑体，原为三号黑体。
添加了三线表格示例。
目前未发现对其他部分造成影响。

### CODE REVIEW

**Comment by JackWzh** [comment]
@summershrimp 表格、图片的标题昨天上传的0.91a版已经更正了，可以跟进一下: )
另外这个表格依赖于哪些包，我这里MiKTeX xelatex有编译错误

> chapter/examples.tex:17: Use of \caption@@setkeys doesn't match its definition
If you say, e.g., `\def\a1{...}', then you must always
put `1' after `\a', since control sequence names are
made up of letters only. The macro here has not been
followed by the required stuff, so I'm ignoring it.

> chapter/examples.tex:17: Use of \@xfootnotemark doesn't match its definition
If you say, e.g., `\def\a1{...}', then you must always
put `1' after `\a', since control sequence names are
made up of letters only. The macro here has not been
followed by the required stuff, so I'm ignoring it.

> chapter/examples.tex:17: Argument of \KV@err has an extra }
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

> Runaway argument?
chapter/examples.tex:17: Paragraph ended before \KV@err was complete
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

> chapter/examples.tex:17: Argument of \KV@errx has an extra }
I've run across a `}' that doesn't seem to match anything.
For example, `\def\a#1{...}' and `\a}' would produce
this error. If you simply proceed now, the `\par' that
I've just inserted will cause me to report a runaway
argument that might be the root of the problem. But if
your `}' was spurious, just type `2' and it will go away.

> Runaway argument?
chapter/examples.tex:17: Paragraph ended before \KV@errx was complete
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

> chapter/examples.tex:17: Missing \endcsname inserted
The control sequence marked <to be read again> should
not appear between \csname and \endcsname.

**Comment by summershrimp** [comment]
我在使用 44a3964 这个版本编译上述表格后，表格标题字号仍为三号。
 图片 
另我在MikTeX和TEXLive 2016 on linux 下编译此表格均不需要额外安装包。//也有可能是自动装了我没注意

**Comment by summershrimp** [comment]
可能是colortbl和makecell

**Comment by JackWzh** [comment]
@summershrimp 我应该把我自己的毕设和这个模板看混了，确实还是小三号，我马上改过来，抱歉 : (
但是这个表格不论是放在模板内编译，还是新建.tex文件编译，最后还是得到我上面的错误，现在感觉是不是包之间有冲突,可以把你用的源码打包发到我邮箱么？
```
\documentclass{ctexbook}

\usepackage{amsfonts,amssymb,amsthm,bm,mathrsfs,mathtools}  %% 公式相关
\usepackage[backend=biber, style=gb7714-2015]{biblatex} %% 参考文献相关
\usepackage{bicaption}
\usepackage{booktabs} %% 表格格式相关
\usepackage{colortbl}
\usepackage[inline]{enumitem} %% list环境相关
\usepackage{fancyhdr} %% 页眉页脚相关
\usepackage{float}
\usepackage{fontspec}
\usepackage[perpage,bottom]{footmisc}
\usepackage[top=4.05cm,bottom=2.82cm,left=2cm,right=2cm]{geometry} %% 页面大小相关
\usepackage{graphicx} %% 插图相关
\usepackage[xetex,hidelinks]{hyperref} %% 交叉引用相关
\usepackage{indentfirst}  %% 首段缩进
\usepackage{listings} %% 代码排版相关
\usepackage{longtable}  %% 跨页表格
\usepackage{makecell} %% 表格相关
\usepackage{multirow} %% 跨行表格相关
\usepackage{rotating} %% 宽表格
\usepackage[titles]{tocloft}
\usepackage{tabularx} %% 表格相关
\usepackage[table]{xcolor}  %% 颜色相关
\usepackage{xltxtra}
\usepackage{ccaption} %% ccaption包因为特殊原因必须在longtable之后加载

\begin{document}
\begin{table}[H]
         \centering
         \bicaption[tab:firstone]{指向一个表格的表目录索引}{一个颇为标准的三线表格 \footnotemark[2]}{Table}{A Table}
         \begin{tabular}{@{}llr@{}} \toprule
             \multicolumn{2}{c}{Item} \\ \cmidrule(r){1-2}
             Animal & Description & Price (\$)\\ \midrule
             Gnat & per gram & 13.65 \\
             & each & 0.01 \\
             Gnu & stuffed & 92.50 \\
             Emu & stuffed & 33.33 \\
             Armadillo & frozen & 8.99 \\ \bottomrule
         \end{tabular}
     \end{table}
     \footnotetext[2]{这个例子来自 \href{http://www.ctan.org/tex-archive/macros/latex/contrib/booktabs/booktabs.pdf}{《Publication quality tables in LATEX》}(booktabs 宏包的文档)。这也是一个在表格中使用脚注的例子，请留意与 threeparttable 实现的效果有何不同。}

\end{document}
```

**Comment by summershrimp** [comment]
我使用的就是在这个分支上的源码进行的编译，在MiKTex上会自动下载依赖包，在Linux上用的texliveonfly 自动下载的依赖
https://github.com/summershrimp/nuaathesis/tree/fix-table-caption

BTW：master分支被reset了？怎么我这个pr突然多出了这么多提交。。

**Comment by JackWzh** [comment]
@summershrimp 我刚刚reset了一下，因为图标编号的问题尽快解决比较好，我不想另外重新提一个commit，就这么弄了，抱歉。。
等我一会儿试一下你的代码

**Comment by JackWzh** [comment]
@summershrimp 确实，你的分支编译没有任何问题，刚刚我试着在我的分支编译了一下，这次又没问题了，很诡异。。。
我用Git不是很熟，而且有commit洁癖。。所以会有一些奇怪的操作，以后我尽量避免

**Comment by summershrimp** [comment]
用rebase或者fastforward就好，不会产生merge commit

**Pull request merged**
